# Generated by Django 5.1.6 on 2025-02-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blocked",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blocked",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="blocked",
            index=models.Index(
                fields=["blocker"], name="core_blocke_blocker_8d4f61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blocked",
            index=models.Index(
                fields=["blocked"], name="core_blocke_blocked_050afe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blocked",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["follower", "following"], name="core_follow_followe_294198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["created_at"], name="core_follow_created_8d82ca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("follower", "following")},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["owner"], name="core_post_owner_i_3a2958_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="core_post_created_2da706_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["user"], name="core_like_user_id_a989fd_idx"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["post"], name="core_like_post_id_777ee2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="commentary",
            index=models.Index(fields=["post"], name="core_commen_post_id_c3ae4a_idx"),
        ),
        migrations.AddIndex(
            model_name="commentary",
            index=models.Index(fields=["user"], name="core_commen_user_id_e7cd61_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="core_profil_user_id_155486_idx"),
        ),
    ]
