# Generated by Django 5.1.6 on 2025-02-09 14:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_blocked_options_alter_commentary_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_post",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.create_custom_path_profile
            ),
        ),
    ]
