# Generated by Django 5.1.6 on 2025-02-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_post_image_post_profile_image_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_post",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/post_images/"
            ),
        ),
    ]
