# Generated by Django 5.1.6 on 2025-02-09 20:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_profile",
            field=models.ImageField(
                blank=True,
                default="static/default_image/default_profile.png",
                null=True,
                upload_to=core.models.create_custom_path_profile,
            ),
        ),
    ]
